os: Previous Visual Studio 2015
version: '{branch}.{build}'
branches:
  only:
  - master
environment:
  matrix:
  - php_ver: 7.1.12
install:
- cmd: cinst wget
build_script:
- cmd: >-
    REM "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\vcvars32.bat"
    REM "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\vcvarsx86_amd64.bat"

    call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
    
    cd C:\projects

    wget -O php-sdk-2.0.13.zip https://github.com/Microsoft/php-sdk-binary-tools/archive/php-sdk-2.0.13.zip

    7z x -y php-sdk-2.0.13.zip -oC:\projects

    C:\projects\php-sdk-binary-tools-php-sdk-2.0.13\bin\phpsdk_setvars.bat

    git clone --depth=1 https://github.com/php/php-src C:\projects\php-src

    mkdir C:\projects\php-src\ext\amf

    xcopy C:\projects\amfext C:\projects\php-src\ext\amf /s /e /y

    wget http://windows.php.net/downloads/php-sdk/deps-7.1-vc14-x64.7z

    7z x -y deps-7.1-vc14-x64.7z -oC:\projects\php-src

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --enable-debug --disable-zts --disable-cgi --disable-com-dotnet --without-mysqlnd --enable-amf --with-prefix=C:\projects\amfext\bin --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development C:\projects\amfext\bin\php.ini

    mkdir C:\projects\amfext\bin\modules.d

    echo extension=php_amf.dll > C:\projects\amfext\bin\modules.d\amf.ini

    C:\projects\amfext\bin\php.exe -m
test_script:
- cmd: C:\projects\amfext\bin\php.exe -doutput_buffering=0 run-tests.php ext\amf -p C:\projects\amfext\bin\php.exe -q
artifacts:
  - path: bin
    name: master
    type: zip

