image: Visual Studio 2017
version: '{branch}.{build}'
branches:
  only:
  - master
install:
    - cinst wget
build_script:
- cmd: >-
    
    cd C:\projects

    wget -O php-sdk-2.1.8.zip https://github.com/Microsoft/php-sdk-binary-tools/archive/php-sdk-2.1.8.zip

    7z x -y php-sdk-2.1.8.zip -oC:\projects

    C:\projects\php-sdk-binary-tools-php-sdk-2.1.8\bin\phpsdk_setvars.bat

    git clone --depth=1 --single-branch --branch="PHP-7.2.9" https://github.com/php/php-src C:\projects\php-src

    mkdir C:\projects\php-src\ext\amf

    xcopy C:\projects\amfext C:\projects\php-src\ext\amf /s /e /y

    cd C:\projects\php-src

    buildconf.bat

    configure.bat --enable-debug --disable-zts --disable-cgi --disable-com-dotnet --without-mysqlnd --enable-amf --with-prefix=C:\projects\amfext\bin --with-php-build=deps

    nmake

    nmake install

    copy php.ini-development C:\projects\amfext\bin\php.ini

    mkdir C:\projects\amfext\bin\modules.d

    echo extension=php_amf.dll > C:\projects\amfext\bin\modules.d\amf.ini

    C:\projects\amfext\bin\php.exe -m
test_script:
  - cmd: C:\projects\amfext\bin\php.exe -doutput_buffering=0 run-tests.php ext\amf -p C:\projects\amfext\bin\php.exe -q
artifacts:
  - path: bin
    name: master
    type: zip

